/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import java.sql.*;
import Database.DbConnection;
/**
 *
 * @author Hiero Nimus
 */
public class TambahDokter extends Template {    
    String nama, nomor_hp, jenis_kelamin, poli, kalimat;

    /**
     * Creates new form DataDokter
     */                        
    public TambahDokter() {
        initComponents();
        
        koneksi = new DbConnection();
        conn = koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDataDokter = new javax.swing.JPanel();
        jLabelTambahDokter = new javax.swing.JLabel();
        jLabelNamaDokter = new javax.swing.JLabel();
        jLabelNomorHP = new javax.swing.JLabel();
        jLabelJenisKelamin = new javax.swing.JLabel();
        jLabelPoli = new javax.swing.JLabel();
        jTextFieldNamaDokter = new javax.swing.JTextField();
        jTextFieldNomorHP = new javax.swing.JTextField();
        jComboBoxJenisKelamin = new javax.swing.JComboBox<>();
        jComboBoxPoli = new javax.swing.JComboBox<>();
        jButtonTambah = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jPanelTampil = new javax.swing.JPanel();
        jScrollPaneTampil = new javax.swing.JScrollPane();
        jTextAreaTampil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDataDokter.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Dokter"));

        jLabelTambahDokter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTambahDokter.setText("Tambah Dokter");

        jLabelNamaDokter.setText("Nama Dokter");

        jLabelNomorHP.setText("Nomor HP");

        jLabelJenisKelamin.setText("Jenis Kelamin");

        jLabelPoli.setText("Poli");

        jTextFieldNamaDokter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNamaDokterFocusLost(evt);
            }
        });

        jTextFieldNomorHP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomorHPFocusLost(evt);
            }
        });

        jComboBoxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jenis kelamin", "Pria", "Wanita" }));
        jComboBoxJenisKelamin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxJenisKelaminFocusLost(evt);
            }
        });

        jComboBoxPoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih poli", "Umum", "Gigi" }));
        jComboBoxPoli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxPoliFocusLost(evt);
            }
        });

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDataDokterLayout = new javax.swing.GroupLayout(jPanelDataDokter);
        jPanelDataDokter.setLayout(jPanelDataDokterLayout);
        jPanelDataDokterLayout.setHorizontalGroup(
            jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTambahDokter)
                    .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                            .addComponent(jButtonKembali)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTambah))
                        .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                            .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                                        .addComponent(jLabelNomorHP)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataDokterLayout.createSequentialGroup()
                                        .addComponent(jLabelJenisKelamin)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                                    .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPoli)
                                        .addComponent(jLabelNamaDokter))
                                    .addGap(37, 37, 37)))
                            .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomorHP)
                                .addComponent(jComboBoxJenisKelamin, 0, 286, Short.MAX_VALUE)
                                .addComponent(jComboBoxPoli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNamaDokter)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelDataDokterLayout.setVerticalGroup(
            jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataDokterLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTambahDokter)
                .addGap(18, 18, 18)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaDokter)
                    .addComponent(jTextFieldNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomorHP)
                    .addComponent(jTextFieldNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJenisKelamin)
                    .addComponent(jComboBoxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoli)
                    .addComponent(jComboBoxPoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTampil.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Data"));

        jTextAreaTampil.setColumns(20);
        jTextAreaTampil.setRows(5);
        jScrollPaneTampil.setViewportView(jTextAreaTampil);

        javax.swing.GroupLayout jPanelTampilLayout = new javax.swing.GroupLayout(jPanelTampil);
        jPanelTampil.setLayout(jPanelTampilLayout);
        jPanelTampilLayout.setHorizontalGroup(
            jPanelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTampilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTampil)
                .addContainerGap())
        );
        jPanelTampilLayout.setVerticalGroup(
            jPanelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTampilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTampil, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDataDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDataDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        // Pengecekan kondisi sebelum menambahkan data
        if (checkNama() && checkNomorHP() && checkJenisKelamin() && checkPoli()) {
            // Jika semua kondisi terpenuhi, tambahkan data
            nama = jTextFieldNamaDokter.getText();
            nomor_hp = jTextFieldNomorHP.getText();
            jenis_kelamin = jComboBoxJenisKelamin.getSelectedItem().toString();
            poli = jComboBoxPoli.getSelectedItem().toString();
            
            insertData();
            clearForm();
            

            // Format kalimat dengan data dokter
            kalimat = "Data Dokter" +
                    "\n\nNama           : " + nama +
                    "\nNomor HP       : " + nomor_hp +
                    "\nJenis Kelamin  : " + jenis_kelamin +
                    "\nPoli           : " + poli +
                    "\n\nBerhasil Ditambahkan";

            // Update tampilan
            jTextAreaTampil.setText(kalimat);
        } else{
            kalimat = "Masukkan data dengan benar!";
            jTextAreaTampil.setText(kalimat);
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jTextFieldNamaDokterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNamaDokterFocusLost
        // TODO add your handling code here:
        checkNama();
    }//GEN-LAST:event_jTextFieldNamaDokterFocusLost

    private void jTextFieldNomorHPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomorHPFocusLost
        // TODO add your handling code here:
        checkNomorHP();
    }//GEN-LAST:event_jTextFieldNomorHPFocusLost

    private void jComboBoxJenisKelaminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxJenisKelaminFocusLost
        // TODO add your handling code here:
        checkJenisKelamin();
    }//GEN-LAST:event_jComboBoxJenisKelaminFocusLost

    private void jComboBoxPoliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxPoliFocusLost
        // TODO add your handling code here:
        checkPoli();
    }//GEN-LAST:event_jComboBoxPoliFocusLost

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        keMenu();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahDokter().setVisible(true);
            }
        });
    }
    
    private boolean checkNama() {
        nama = jTextFieldNamaDokter.getText();
        String errorNama = "ERROR: Nama hanya boleh terdiri dari huruf.";

        boolean isValidNama = nama.matches("[a-zA-Z\\s]+");

        if (!isValidNama) {
            jTextAreaTampil.setText(errorNama);
        }

        return isValidNama;
    }

    private boolean checkNomorHP() {
        nomor_hp = jTextFieldNomorHP.getText();
        String errorNomorHP = "ERROR: Nomor HP hanya boleh terdiri dari angka.";

        boolean isValidNomorHP = nomor_hp.matches("[0-9]+");

        if (!isValidNomorHP) {
            jTextAreaTampil.setText(errorNomorHP);
        }

        return isValidNomorHP;
    }

    private boolean checkJenisKelamin() {
        String selectedJenisKelamin = jComboBoxJenisKelamin.getSelectedItem().toString();
        String errorJenisKelamin = "ERROR: Pilih jenis kelamin yang valid.";

        if ("Pilih jenis kelamin".equals(selectedJenisKelamin)) {
            jTextAreaTampil.setText(errorJenisKelamin);
            return false;
        }

        return true;
    }

    private boolean checkPoli() {
        String selectedPoli = jComboBoxPoli.getSelectedItem().toString();
        String errorPoli = "ERROR: Pilih poli yang valid.";

        if ("Pilih poli".equals(selectedPoli)) {
            jTextAreaTampil.setText(errorPoli);
            return false;
        }

        return true;
    }
    
    private boolean insertData(){
        try{
            stmt = conn.createStatement();
            int insert = stmt.executeUpdate("INSERT INTO dokter(nama, nomor_hp, jenis_kelamin, poli) VALUES('" + 
                    nama + "', '" + nomor_hp + "', '" + jenis_kelamin + "', '" + poli + "')");

            if(insert == 1){
                JOptionPane.showMessageDialog(rootPane, "Data tersimpan.");
            }
            return true;
        } catch (SQLException ex) {
            // Tangani kesalahan SQL
            JOptionPane.showMessageDialog(null, "Kesalahan SQL: " + ex.getMessage());
        }
        return false;
    }
    
    private void clearForm(){
        jTextFieldNamaDokter.setText("");
        jTextFieldNomorHP.setText("");
        jComboBoxJenisKelamin.setSelectedIndex(0);
        jComboBoxPoli.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBoxJenisKelamin;
    private javax.swing.JComboBox<String> jComboBoxPoli;
    private javax.swing.JLabel jLabelJenisKelamin;
    private javax.swing.JLabel jLabelNamaDokter;
    private javax.swing.JLabel jLabelNomorHP;
    private javax.swing.JLabel jLabelPoli;
    private javax.swing.JLabel jLabelTambahDokter;
    private javax.swing.JPanel jPanelDataDokter;
    private javax.swing.JPanel jPanelTampil;
    private javax.swing.JScrollPane jScrollPaneTampil;
    private javax.swing.JTextArea jTextAreaTampil;
    private javax.swing.JTextField jTextFieldNamaDokter;
    private javax.swing.JTextField jTextFieldNomorHP;
    // End of variables declaration//GEN-END:variables
}
