
import Database.DbConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hiero Nimus
 */
public class Template extends javax.swing.JFrame {
    Connection conn;
    Statement stmt;
    ResultSet rs;
    DbConnection koneksi;

    /**
     * Creates new form Menu
     */
    public Template() {
        initComponents();
        this.setTitle("Rekam Medis Puskesmas Sumber Mulia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();
        jMenuData = new javax.swing.JMenu();
        jMenuItemTambahRekamMedis = new javax.swing.JMenuItem();
        jMenuItemTabelRekamMedis = new javax.swing.JMenuItem();
        jMenuItemTambahDokter = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuUser.setText("User");

        jMenuItemLogOut.setText("Log Out");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemLogOut);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemKeluar);

        jMenuBarMenu.add(jMenuUser);

        jMenuData.setText("Data");

        jMenuItemTambahRekamMedis.setText("Tambah Rekam Medis");
        jMenuItemTambahRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTambahRekamMedisActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemTambahRekamMedis);

        jMenuItemTabelRekamMedis.setText("Lihat Rekam Medis");
        jMenuItemTabelRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTabelRekamMedisActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemTabelRekamMedis);

        jMenuItemTambahDokter.setText("Tambah Dokter");
        jMenuItemTambahDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTambahDokterActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemTambahDokter);

        jMenuItem1.setText("Cari Riwayat Pasien");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItem1);

        jMenuBarMenu.add(jMenuData);

        setJMenuBar(jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void jMenuItemTambahDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTambahDokterActionPerformed
        // TODO add your handling code here:
        keTambahDokter();

    }//GEN-LAST:event_jMenuItemTambahDokterActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Login formLogin = new Login();
        formLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jMenuItemTambahRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTambahRekamMedisActionPerformed
        // TODO add your handling code here:
        keTambahRekamMedis();   
    }//GEN-LAST:event_jMenuItemTambahRekamMedisActionPerformed

    private void jMenuItemTabelRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTabelRekamMedisActionPerformed
        // TODO add your handling code here:
        keTabelRekamMedis();
    }//GEN-LAST:event_jMenuItemTabelRekamMedisActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        keRiwayatPasien();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    protected void keMenu(){
        dispose();
        
        Menu formMenu = new Menu();
        formMenu.setVisible(true); 
    }
    
    protected void keTambahDokter(){
        dispose();
        
        TambahDokter formTambahDokter = new TambahDokter();
        formTambahDokter.setVisible(true);
    }
    
    protected void keTambahRekamMedis(){
        dispose();
        
        TambahRekamMedis formTambahRekamMedis = new TambahRekamMedis();
        formTambahRekamMedis.setVisible(true);  
    }
    
    protected void keTabelRekamMedis(){
        dispose();
        
        TabelRekamMedis formTabelRekamMedis = new TabelRekamMedis();
        formTabelRekamMedis.setVisible(true);    
    }
    
    protected void keRiwayatPasien(){
        dispose();
        
        RiwayatPasien formRiwayatPasien = new RiwayatPasien();
        formRiwayatPasien.setVisible(true);    
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemTabelRekamMedis;
    private javax.swing.JMenuItem jMenuItemTambahDokter;
    private javax.swing.JMenuItem jMenuItemTambahRekamMedis;
    private javax.swing.JMenu jMenuUser;
    // End of variables declaration//GEN-END:variables
}
